databases:
  - name: student-management-app
    databaseName: student-management-app
    user: student-management-app

services:
  - type: web
    name: student-management-app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: student-management-app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false